### ISSUE TITLE
Add-dividing-line

### ISSUE THREAD

**Issue by kojesung** [Nice-HUD/Nice-HUD#10]
## Problem Description
Add a separating line to distinguish between the player's ship HUD information and the area where the ship is displayed.

## Todo List

-   [ ] Modify the DrawManager to include a method for rendering a horizontal line.
-   [ ] Update the GameScreen class to call this new method and draw the separating line.
-   [ ] Ensure the line doesn't interfere with the gameplay area or other HUD elements.

## Feature Description
A horizontal line will be added to the game screen to visually separate the area containing the player's ship HUD information from the main gameplay area where the ship is displayed.

## Additional Information
The line should be subtle enough not to distract from gameplay but clear enough to provide a visual separation. Consider using a color that complements the existing UI elements. The exact position of the line may need to be adjusted based on the current layout of the HUD and gameplay area.
