### ISSUE TITLE
[HOTFIX]  Error with module and JDK recognition

### ISSUE THREAD

**Issue by DongWonLee2** [Nice-HUD/Nice-HUD#22]
## Problem Description

When pulling, an error occurs that requires resetting the module and JDK in the project.

## Todo List

-   [ ] Create hotfix branch
-   [ ] Delete .idea folder content from .gitignore
-   [ ] Delete existing git tracking cache

## Additional Information

The .idea folder is a file for managing projects in IntelliJ. It should not be modified or deleted directly.
