### ISSUE TITLE
update-life-graphic

### ISSUE THREAD

**Issue by DongWonLee2** [Nice-HUD/Nice-HUD#3]
### Title: [Feature] <Update-Life-Graphic>

---

### Summary
Modifying Life Graphics.

### Feature Description
1. Change the existing ship graphics life on the game screen to heart graphics
2. Pixel Graphics Study Request

### TODO
- [x] Modify a graphic file
- [x] Modify a DrawManager.java
- [x] Modify a Entity.java
