### ISSUE TITLE
[Hotfix] Restore .idea Files

### ISSUE THREAD

**Issue by DongWonLee2** [Nice-HUD/Nice-HUD#33]
### Problem Description
The `.idea` files were mistakenly removed, causing issues with the IDE configuration. These files need to be restored to their original state.

---

### Todo List
- [x] Create hotfix branch
- [x] Add .idea folder content to .gitignore
- [x] Delete existing git tracking cache

### Additional Information
- If there are other team members who have a correct version of the `.idea` files, those should be shared and restored.
- Review the `.gitignore` file to ensure the correct files are included/excluded.
