### ISSUE TITLE
Modify-TopBottom-Background-Color

### ISSUE THREAD

**Issue by aeioiie** [Nice-HUD/Nice-HUD#42]
## Problem Description

Modify the background color of the upper part of the top green line and the lower part of the bottom green line.

## Todo List

-   [x] Change the color of the backgrounds to black.
-   [x] Modify the draw method of the GameScreen class.
-   [x] Add the drawRect method of the DrawManagerImpl class.

## Feature Description

The background color of the top and bottom will be modified to black for the better gameplay.
