### ISSUE TITLE
[FEATURE] Add the status information of  2P 

### ISSUE THREAD

**Issue by LeeHyunWoo02** [Nice-HUD/Nice-HUD#46]
## Problem Description

With the addition of a two-player game feature
Adds the ability to display the status of the second player on the screen.

## Todo List

-   [x] Add the remaining life of 2P on GameScreen
-   [x] Add 2P movement speed on GameScreen
-   [x] Add 2P launch speed on GameScreen

## Feature Description

The status information of 2p is displayed on the game screen.
