### ISSUE TITLE
Modify-Ships-Color

### ISSUE THREAD

**Issue by aeioiie** [Nice-HUD/Nice-HUD#48]
## Problem Description

Modify the color of the ships.

## Todo List
-   [x] Set player1 ship color to red for better visibility.
-   [x] Set player2 ship color to blue for easy differentiation between players.
-   [x] Improve overall game visual clarity with distinct ship colors.

## Feature Description

Change the color of ship1(player1) to red and ship2(player2) to blue to distinguish each of them.
